import copy

dict_plantilla_excel = {
    "Prisma": {
        "URL Prisma": {},
        "Año de Publicación": {},
        "Tipo": {},
        "Título": {},
        "Fuente": {},
        "ISSN": {},
        "ISBN": {},
        "Datos de la Publicación": {},
        "Editorial": {},
        "Autores": {},
        "Autores grupales": {},
        "Autores US": {},
        "Autores grupales US": {},
        "Autoría Grupal Exclusiva Sí/No": {},
        "Total Autores": {},
        "Total Autores grupales": {},
        "Autoría preferente": {},
        "Afiliaciones": {},
        "Afiliaciones Internacionales Sí/No": {},
        "Afiliaciones Internacionales": {},
        "DOI": {},
        "Cód. WOS": {},
        "Cód. Scopus": {},
        "Cód. PubMed": {},
        "Id. idUS": {},
        "Cód. Dialnet": {},
        "Vía Acceso": {},
        "Dialnet": {},
    },
    "Citas": {
        "URL Prisma": {},
        "Año de Publicación": {},
        "Tipo": {},
        "Editorial": {},
        "Título": {},
        "Fuente": {},
        "DOI": {},
        "Cód. WOS": {},
        "Citas en WOS": {},
        "Cód. Scopus": {},
        "Citas en Scopus": {},
        "Cód. Dialnet": {},
        "Citas en Dialnet": {},
    },
    "JIF": {
        "URL Prisma": {},
        "Año de Publicación": {},
        "Tipo": {},
        "Editorial": {},
        "Título": {},
        "Fuente": {},
        "ISSN": {},
        "DOI": {},
        "Total Autores": {},
        "Cód. WOS": {},
        "Citas en WOS": {},
        "JIF": {},
        "Categorías JIF-SCIE": {},
        "Mejor Cuartil JIF-SCIE": {},
        "Categorías Mejor Cuartil JIF-SCIE": {},
        "Mejor Decil JIF-SCIE": {},
        "Categorías Mejor Decil JIF-SCIE": {},
        "Mejor Tercil JIF-SCIE": {},
        "Categorías Mejor Tercil JIF-SCIE": {},
        "Categorías JIF-SSCI": {},
        "Mejor Cuartil JIF-SSCI": {},
        "Categorías Mejor Cuartil JIF-SSCI": {},
        "Mejor Decil JIF-SSCI": {},
        "Categorías Mejor Decil JIF-SSCI": {},
        "Mejor Tercil JIF-SSCI": {},
        "Categorías Mejor Tercil JIF-SSCI": {},
    },
    "JCI": {
        "URL Prisma": {},
        "JCI": {},
        "Categorías JCI": {},
        "Mejor Cuartil JCI": {},
        "Categorías Mejor Cuartil JCI": {},
        "Mejor Decil JCI": {},
        "Categorías Mejor Decil JCI": {},
        "Mejor Tercil JCI": {},
        "Categorías Mejor Tercil JCI": {},
    },
    "SJR": {
        "URL Prisma": {},
        "Año de Publicación": {},
        "Tipo": {},
        "Editorial": {},
        "Título": {},
        "Fuente": {},
        "ISSN": {},
        "DOI": {},
        "Total Autores": {},
        "Cód. Scopus": {},
        "Citas en Scopus": {},
        "SJR": {},
        "Categorías SJR": {},
        "Mejor Cuartil SJR": {},
        "Categorías Mejor Cuartil SJR": {},
        "Mejor Decil SJR": {},
        "Categorías Mejor Decil SJR": {},
        "Mejor Tercil SJR": {},
        "Categorías Mejor Tercil SJR": {},
    },
    "Dialnet": {
        "URL Prisma": {},
        "Año de Publicación": {},
        "Tipo": {},
        "Editorial": {},
        "Título": {},
        "Fuente": {},
        "ISSN": {},
        "DOI": {},
        "Nº Autores": {},
        "Autoría preferente": {},
        "Cód. Dialnet": {},
        "Citas en Dialnet": {},
        "IDR": {},
        "Categorías IDR": {},
        "Mejor Cuartil IDR": {},
        "Categorías Mejor Cuartil IDR": {},
        "Mejor Percentil IDR": {},
        "Categorías Mejor Percentil IDR": {},
    },
    "CiteScore": {
        "URL Prisma": {},
        "Año de Publicación": {},
        "Tipo": {},
        "Editorial": {},
        "Título": {},
        "Fuente": {},
        "ISSN": {},
        "DOI": {},
        "Total Autores": {},
        "Cód. Scopus": {},
        "Citas en Scopus": {},
        "CiteScore": {},
        "Categorías CiteScore": {},
        "Mejor Cuartil CiteScore": {},
        "Categorías Mejor Cuartil CiteScore": {},
        "Mejor Decil CiteScore": {},
        "Categorías Mejor Decil CiteScore": {},
        "Mejor Tercil CiteScore": {},
        "Categorías Mejor Tercil CiteScore": {},
    },
}


def get_dict_plantilla_excel():
    return copy.deepcopy(dict_plantilla_excel)
