publicacion = {
    "titulo": "Measurement of the angular distribution of fission fragments using a PPAC assembly at CERN n-TOF",
    "titulo_alternativo": "",
    "tipo": "Artículo",
    "autores": [
        {
            "firma": "Tarrío, D.",
            "tipo": "Autor/a",
            "orden": 1,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Tarrío, D."}],
            "afiliaciones": [],
        },
        {
            "firma": "Leong, L. S.",
            "tipo": "Autor/a",
            "orden": 2,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Leong, L. S."}],
            "afiliaciones": [],
        },
        {
            "firma": "Audouin, Laurent",
            "tipo": "Autor/a",
            "orden": 3,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Audouin, Laurent"}],
            "afiliaciones": [],
        },
        {
            "firma": "Duran, I.",
            "tipo": "Autor/a",
            "orden": 4,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Duran, I."}],
            "afiliaciones": [],
        },
        {
            "firma": "Paradela, C.",
            "tipo": "Autor/a",
            "orden": 5,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Paradela, C."}],
            "afiliaciones": [],
        },
        {
            "firma": "Tassan-Got, L.",
            "tipo": "Autor/a",
            "orden": 6,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Tassan-Got, L."}],
            "afiliaciones": [],
        },
        {
            "firma": "Le Naour, C.",
            "tipo": "Autor/a",
            "orden": 7,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Le Naour, C."}],
            "afiliaciones": [],
        },
        {
            "firma": "Bacri, C.O.",
            "tipo": "Autor/a",
            "orden": 8,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Bacri, C.O."}],
            "afiliaciones": [],
        },
        {
            "firma": "Petitbon, V.",
            "tipo": "Autor/a",
            "orden": 9,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Petitbon, V."}],
            "afiliaciones": [],
        },
        {
            "firma": "Cortés Giraldo, Miguel Antonio",
            "tipo": "Autor/a",
            "orden": 10,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Cortés Giraldo, Miguel Antonio"}],
            "afiliaciones": [],
        },
        {
            "firma": "Quesada Molina, José Manuel",
            "tipo": "Autor/a",
            "orden": 11,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Quesada Molina, José Manuel"}],
            "afiliaciones": [],
        },
        {
            "firma": "Žugec, P.",
            "tipo": "Autor/a",
            "orden": 12,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Žugec, P."}],
            "afiliaciones": [],
        },
        {
            "firma": "Praena Rodríguez, Javier",
            "tipo": "Autor/a",
            "orden": 13,
            "contacto": "N",
            "ids": [{"tipo": "idus", "valor": "Praena Rodríguez, Javier"}],
            "afiliaciones": [],
        },
    ],
    "año_publicacion": "2014",
    "identificadores": [
        {"tipo": "doi", "valor": "10.1016/j.nima.2013.12.056"},
        {"tipo": "idus", "valor": "11441/95195"},
    ],
    "datos": [
        {"tipo": "volumen", "valor": "743"},
        {"tipo": "pag_inicio", "valor": "79"},
        {"tipo": "pag_fin", "valor": "85"},
    ],
    "fuente": {
        "titulo": "Nuclear Instruments and Methods in Physics Research, Section A: Accelerators, Spectrometers, Detectors and Associated Equipment, 743, 79-85.",
        "tipo": "Libro",
        "editoriales": [
            {
                "nombre": "Elsevier",
                "tipo": "Otros",
                "pais": "Desconocido",
                "url": None,
            },
        ],
        "identificadores": [{"tipo": "issn", "valor": "0168-9002"}],
        "datos": [
            {
                "tipo": "url",
                "valor": "https://www.sciencedirect.com/science/article/pii/S016890021303056X",
            },
        ],
    },
    "financiacion": [
        {
            "proyecto": "FPA2011-24553",
            "entidad_financiadora": "Ministerio de Ciencia e Innovación",
            "agencia": "",
            "pais": "España",
            "ror": "05r0vyz12",
        },
    ],
    "fechas_publicacion": [
        {
            "tipo": "publicacion",
            "mes": 1,
            "agno": 2014,
            "dia": None,
        },
    ],
    "acceso_abierto": [
        {
            "valor": "gold",
            "origen": "upw",
        },
    ],
}
